In [ ]:
import pandas as pd
pd.__version__

'1.0.3'

In [ ]:
dict_data = {'CO':300,'MX':400,'CH':200}
dict_data

{'CH': 200, 'CO': 300, 'MX': 400}

In [ ]:
pd.Series(dict_data)

CO    300
MX    400
CH    200
dtype: int64

In [ ]:
dict_data = {'CH': [100, 800, 200], 'CO': [100, 200, 300], 'MX': [300, 500, 400]}
dict_data

{'CH': [100, 800, 200], 'CO': [100, 200, 300], 'MX': [300, 500, 400]}

In [ ]:
df = pd.DataFrame(dict_data)
df

    CH   CO   MX
0  100  100  300
1  800  200  500
2  200  300  400

In [ ]:
import numpy as np

In [ ]:
dict_data = {
    'edad' :     [ 10, 9, 13, 14, 12, 11, 12],
    'cm' : [ 115, 110, 130, 155, 125, 120, 125],
    'pais' :    [ 'co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch'],
    'genero' :  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
    'Q1' : [ 5, 10, 8, np.nan, 7, 8, 3],
    'Q2' : [ 7, 9, 9, 8, 8, 8, 9.]
}
dict_data

{'Q1': [5, 10, 8, nan, 7, 8, 3],
 'Q2': [7, 9, 9, 8, 8, 8, 9.0],
 'cm': [115, 110, 130, 155, 125, 120, 125],
 'edad': [10, 9, 13, 14, 12, 11, 12],
 'genero': ['M', 'F', 'F', 'M', 'M', 'M', 'F'],
 'pais': ['co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch']}

In [ ]:
df = pd.DataFrame(dict_data, index = ['ana','benito','camilo','daniel','erika','fabian','gabriela'])
df

          edad   cm pais genero    Q1   Q2
ana         10  115   co      M   5.0  7.0
benito       9  110   mx      F  10.0  9.0
camilo      13  130   co      F   8.0  9.0
daniel      14  155   mx      M   NaN  8.0
erika       12  125   mx      M   7.0  8.0
fabian      11  120   ch      M   8.0  8.0
gabriela    12  125   ch      F   3.0  9.0

In [ ]:
df.index

Index(['ana', 'benito', 'camilo', 'daniel', 'erika', 'fabian', 'gabriela'], dtype='object')

In [ ]:
df.columns

Index(['edad', 'cm', 'pais', 'genero', 'Q1', 'Q2'], dtype='object')

In [ ]:
df.values

array([[10, 115, 'co', 'M', 5.0, 7.0],
       [9, 110, 'mx', 'F', 10.0, 9.0],
       [13, 130, 'co', 'F', 8.0, 9.0],
       [14, 155, 'mx', 'M', nan, 8.0],
       [12, 125, 'mx', 'M', 7.0, 8.0],
       [11, 120, 'ch', 'M', 8.0, 8.0],
       [12, 125, 'ch', 'F', 3.0, 9.0]], dtype=object)

In [ ]:
df['edad']

ana         10
benito       9
camilo      13
daniel      14
erika       12
fabian      11
gabriela    12
Name: edad, dtype: int64

In [ ]:
df[['edad','cm','Q1']]

          edad   cm    Q1
ana         10  115   5.0
benito       9  110  10.0
camilo      13  130   8.0
daniel      14  155   NaN
erika       12  125   7.0
fabian      11  120   8.0
gabriela    12  125   3.0

In [ ]:
df.loc['ana',['edad','cm','Q1']]

edad     10
cm      115
Q1        5
Name: ana, dtype: object

In [ ]:
df.loc[['ana','erika'],['edad','cm','Q1']]

       edad   cm   Q1
ana      10  115  5.0
erika    12  125  7.0

In [ ]:
print(df.iloc[[4],2])

erika    mx
Name: pais, dtype: object

In [ ]:
df.loc['daniel','Q1']

nan

In [ ]:
df

          edad   cm pais genero    Q1   Q2
ana         10  115   co      M   5.0  7.0
benito       9  110   mx      F  10.0  9.0
camilo      13  130   co      F   8.0  9.0
daniel      14  155   mx      M   NaN  8.0
erika       12  125   mx      M   7.0  8.0
fabian      11  120   ch      M   8.0  8.0
gabriela    12  125   ch      F   3.0  9.0

In [ ]:
df.iloc[2,1]

130

In [ ]:
df.iloc[[2,4,5],[1,3]]

         cm genero
camilo  130      F
erika   125      M
fabian  120      M

In [ ]:
df['edad'] >= 12

ana         False
benito      False
camilo       True
daniel       True
erika        True
fabian      False
gabriela     True
Name: edad, dtype: bool

In [ ]:
df[df['edad'] >= 12]

          edad   cm pais genero   Q1   Q2
camilo      13  130   co      F  8.0  9.0
daniel      14  155   mx      M  NaN  8.0
erika       12  125   mx      M  7.0  8.0
gabriela    12  125   ch      F  3.0  9.0

In [ ]:
df[(df['edad'] >= 12) & (df['pais'] == 'mx')]

        edad   cm pais genero   Q1   Q2
daniel    14  155   mx      M  NaN  8.0
erika     12  125   mx      M  7.0  8.0

In [ ]:
df.query('edad > 12')

        edad   cm pais genero   Q1   Q2
camilo    13  130   co      F  8.0  9.0
daniel    14  155   mx      M  NaN  8.0

In [ ]:
df.query("(edad >= 12) & (cm < 130) & (Q1 > 5)")['Q2'].T

erika    8.0
Name: Q2, dtype: float64

In [ ]:
df[df['Q2'] >= df['Q1']]

          edad   cm pais genero   Q1   Q2
ana         10  115   co      M  5.0  7.0
camilo      13  130   co      F  8.0  9.0
erika       12  125   mx      M  7.0  8.0
fabian      11  120   ch      M  8.0  8.0
gabriela    12  125   ch      F  3.0  9.0